=== PonteIneptique/DTS-validator/schemas/entry_response.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/mromanello/DTS-validator/main/schemas/entry_response_schema.json",
    "type": "object",
    "properties": {
        "@context": {"type": "string"},
        "@id": {"type": "string"},
        "@type": {"type": "string"},
        "dtsVersion": {
            "type": "string",
            "enum": ["1-alpha"]
        },
        "collection": {"type": "string"},
        "document": {"type": "string"},
        "navigation": {"type": "string"}
    },
    "required": [
        "@context", "@id", "@type", "dtsVersion", "collection", "document", "navigation"
    ]
}

=== PonteIneptique/DTS-validator/tests/data/entry_response_from_docs.json
{
    "@context": "https://distributed-text-services.github.io/specifications/context/1-alpha1.json",
    "dtsVersion": "1-alpha",
    "@id": "/dts/api/",
    "@type": "EntryPoint",
    "collection": "/dts/api/collection/{?id,page,nav}",
    "navigation" : "/dts/api/navigation/{?resource,ref,start,end,down,tree,page}",
    "document": "/dts/api/document/{?resource,ref,start,end,tree,mediaType}"
}
